<?php
/** @var \Perspective\ProductPagePractice\ViewModel\ProductData $viewModel */
$viewModel = $block->getData('viewModel');

$product = $viewModel->getCurrentProduct();
$category = $viewModel->getCurrentCategory();
?>

<h3>Data from registry with helper</h3>
    <h4>Product:
        <?= $product->getId() ?> |
        <?= $product->getName() ?> |
        <?= $product->getSku() ?>
    </h4>

    <h4>Category:
        <?= $category->getId() ?> |
        <?= $category->getName() ?>
    </h4>

