<?php
/** @var \Perspective\PaymentTools\ViewModel\PaymentMethods $viewModel */
$viewModel = $block->getData('viewModel');
$paymentMethods = $viewModel->getPaymentMethods();
?>

<h3>Завдання 2.6 - Get list of Payment Methods</h3>

<ul>
    <?php foreach ($paymentMethods as $method): ?>
        <li>
            Title: <?= $method->getTitle() ?><br>
            Code: <?= $method->getCode() ?><br>
        </li>
        <hr>
    <?php endforeach; ?>
</ul>