<?php 
/** @var \Perspective\TutorialEntity\ViewModel\EntityZavd2 $viewModel */
/** @var \Magento\Catalog\Model\Product $product */ // для ошибки от intelephense
$viewModel = $block->getData('viewModel');
$products = $viewModel->getFilteredProducts('T', 9.0, 20.0, 10); // (Фільтри: Літера, МінЦіна, МаксЦіна, КількЗаписів)
?>
<h2>Створити з адмінки простий (simple) продукт.
         Отримати інформацію про перші N(10) продукти, name яких починається на певну
          літеру Letter(T), ціни знаходяться в діапазоні MinPrice(9) - MaxPrice(20),
           продукти відсортовані за зменшенням ціни. Результат вивести на нову сторінку
            magento, надати name і price продуктів. Передбачити, щоб новий продукт
             потрапив до результату.</h2>
             <hr>
<h2>Продукти, які починаються з "T" і з ціною 9–20</h2>
<?php foreach ($products as $product): ?>
    <h3><?= $product->getName(); ?> — <?= number_format($product->getPrice(), 2) ?></h3>
<?php endforeach; ?>