<?php 
/** @var \Perspective\TutorialEntity\ViewModel\EntityZavd4 $viewModel */
$viewModel = $block->getData('viewModel');
$categories = $viewModel->getAllCategories();
?>

<h2>Створити нову категорію. Включити продукт із пункту 2 до цієї категорії.
     Отримати список усіх категорій та вивести доступні дані
      про категорії ( getData())</h2>
<hr>

<h2>Список усіх категорій</h2>
<?php foreach ($categories as $category): ?>
    <h3>Name: <?= $category->getName(); ?></h3>
    <ul>
        <li>ID: <?= $category->getId(); ?></li>
        <li>Created At: <?= $category->getCreatedAt(); ?></li>
    </ul>
    <hr>
<?php endforeach; ?>