<?php
/** @var \Perspective\ProductTools\ViewModel\FilteredProducts $viewModel */
$viewModel = $block->getData('viewModel');

$categoryId = 23;
$priceMin = 50;
$priceMax = 60;

$productCollection = $viewModel->getFilteredProducts($categoryId, $priceMin, $priceMax);
?>

<h3>Завдання 3 - Get Filtered Products by Category and Price</h3>

<h3>
    Категорія:Women - Tops - Jackets |
    <?=$priceMin?> &lt; Price &lt; <?=$priceMax?>
</h3>
<ul>
    <?php foreach ($productCollection as $product): ?>
        <li>
            <?= $product->getName(); ?>
            (<?= $product->getSku(); ?>) - 
            <?= $product->getFormattedPrice($product->getPrice()); ?>
        </li>
    <?php endforeach; ?>
</ul>
