<?php
/** @var \Perspective\ProductTools\ViewModel\ProductCategories $viewModel */
$viewModel = $block->getData('viewModel');

$productId = 15; // Set the product ID

$productName = $viewModel->getProductNameById($productId);
$categoryNames = $viewModel->getCategoryNamesByProductId($productId);
?>

<h2>Завдання 1.1 - Get Categories from specific Product</h2>

<h2>Product(ID): <?= $productName ?> (<?= $productId ?>)</h2>
<h2>Categories:</h2>
<ul>
    <?php foreach ($categoryNames as $name): ?>
        <li><?= $name ?></li>
    <?php endforeach; ?>
</ul>
