<?php
/** @var \Perspective\ProductTools\ViewModel\ProductImage $viewModel */
$viewModel = $block->getData('viewModel');

$productId = 1; // Product ID

$product = $viewModel->getProductById($productId);
$imageInfo = $viewModel->getImageInfo($product);
?>

<h3>Завдання 2.2 - Get Product Image Info (URL, Width, Height)</h3>

<h3>Product(ID): <?= $product->getName() ?> (<?= $product->getId() ?>)</h3>

<ul>
    <li>Image URL: <?= $imageInfo['url'] ?></li>
    <li>Width: <?= $imageInfo['width'] ?></li>
    <li>Height: <?= $imageInfo['height'] ?></li>
</ul>

<h3>Preview:</h3>
<img
    src="<?= $imageInfo['url'] ?>"
    width="<?= $imageInfo['width'] ?>" 
    height="<?= $imageInfo['height'] ?>" 
/>