<?php
/** @var \Perspective\ProductTools\ViewModel\ProductsByCategory $viewModel */
$viewModel = $block->getData('viewModel');

$categoryId = 5;

$category = $viewModel->getCategoryById($categoryId);
$productCollection = $viewModel->getProductsByCategoryId($categoryId);
?>

<h2>Завдання 1.3 - Get Product Collection by Category</h2>

<h3>Категорія(ID): <?= $category->getName(); ?> (<?= $categoryId ?>)</h3>
<ul>
    <?php foreach ($productCollection as $product): ?>
        <li><?= $product->getName(); ?></li>
    <?php endforeach; ?>
</ul>
