<?php
/** @var \Perspective\ProductDiscountTimer\ViewModel\DiscountDetails $viewModel */
$viewModel = $block->getData('viewModel');

$spec = $viewModel->getSpecialPriceData();
$rules = $viewModel->getUnifiedDiscountRules();
$currencySymb = $viewModel->getCurrencySymbol();
$catalogRuleCheaperThanSpecial = $viewModel->isCatalogRuleCheaperThanSpecial();

// Check if there are discount rules
if (!empty($rules)) { 
    //get end time for the first rule
    if (!empty($rules[0]['to_time'])) {
        $end = new \DateTime($rules[0]['to_time'], new \DateTimeZone('UTC'));
    } else {
        $end = null;
    }

    // Format discount value (percent or currency)
    function discountFormat($rules, $i, $currencySymb)
    {
        $discount = number_format($rules[$i]['action_amount'], 1);
        if ($rules[$i]['action_operator'] == 'by_percent') {
            $discount = $discount . '%';
        } else {
            $discount = $currencySymb . $discount;
        }
        if ($rules[$i]['rule_type'] === 'catalog_rule') {
            $discount = '-' . $discount;
        }
        return $discount;
    }

    //First expiring rule\special price
    if (!$catalogRuleCheaperThanSpecial) {
        if (!empty($spec)) {
            echo('<h2>Used special price: ' . $currencySymb . number_format($spec['action_amount'], 2) . '</h2>');
        }

        foreach ($rules as $i => $rule) {
            if ($rule['rule_type'] === 'special') {
                unset($rules[$i]);
                break;
            }
        }
    } else {
        $discount = discountFormat($rules, 0 , $currencySymb);
        echo('<h2>Next expiring discount rule: "' . $rules[0]['rule_name'] . '" (' . $discount . ')</h2>');
        unset($rules[0]); 
    }

    //Timer widget
    echo '<h2>Remaining time:<div id="countdown" data-end="' . $end->format('c') . '"></div></h2>';

    //List of another rules
    if (!empty($rules)) {
        echo('<h3>Another discount rules:</h3><h4>');
    }

    foreach ($rules as $i => $rule) {
        $discount = discountFormat($rules, $i , $currencySymb);
        
        $used = ' |';
        if (
            (!$catalogRuleCheaperThanSpecial && $rule['rule_type'] === 'catalog_rule') ||
            ($catalogRuleCheaperThanSpecial && $rule['rule_type'] === 'special')
        ) {
            $used = $used . ' Not used';
        }
        echo($i . ') ' . $rule['rule_name'] . ' (' . $discount . ') | Ending: ' . $rule['to_time'] . $used . '<br>');
    }
}
?>
</h4>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "countdownTimer": {
                    "component": "Perspective_ProductDiscountTimer/js/countdown-init"
                }
            }
        }
    }
}
</script>