<?php
/** @var \Perspective\CustomerTools\ViewModel\CustomerCollection $viewModel */
$viewModel = $block->getData('viewModel');
$customerCollection = $viewModel->getCustomerCollection();
?>

<h3>Завдання 2.3 - Get Customer Collection</h3>

<ul>
    <?php foreach ($customerCollection as $customer): ?>
        <li>
            <?= $customer->getFirstname() ?> <?= $customer->getLastname() ?>
            (<?= $customer->getEmail() ?>)
        </li>
    <?php endforeach; ?>
</ul>
