<?php
/** @var \Perspective\HomeworkSocialProduct\ViewModel\Social $viewModel */
$viewModel = $block->getData('viewModel');

if ($viewModel->isModuleEnabled() && $viewModel->isSocialAttributeEnabled()):
      echo ('<h3>Social discount rate: ' . $viewModel->getSocialDiscountRate() . '%<br>' .
            'Price with discount: ' . $viewModel->getSocialPrice() . $viewModel->getCurrencySymbol()
            . '</h3>');
endif;
?>