<?php
/** @var \Perspective\HomeworkAirFreight\ViewModel\AirFreight $viewModel */
$viewModel = $block->getData('viewModel');

if ($viewModel->isModuleEnabled() &&
    $viewModel->getAirFreightValue() !== 'none' &&
    $viewModel->getAirFreightValue() !== null &&
    $viewModel->isOverweighted()) 
{
    echo ('<h3>' . $viewModel->getAirFreightLabel() . ' shipping includes additional '
        . $viewModel->getOverweightFee() . $viewModel->getCurrencySymbol()
        . ' fee.</h3><br>');
}
?>