<?php
/** @var \Perspective\HomeworkDatabase\ViewModel\GetFullConsultationCost $viewModel */
$viewModel = $block->getData('viewModel');


$collection = $viewModel->getConsultationCollection();

echo '<h3>Завдання 8: Get Full Consultation Cost</h3>';
echo ('<h3>Title(ID) - FullCost (Discount%):</h3><h4>');
foreach ($collection as $consultation): ?>
        <?=$consultation->getData('title')?>
        (<?=$consultation->getData('consultation_id')?>) - 
        <?=$consultation->getData('price_per_hour') *
            $consultation->getData('duration_hours') * 
            (1 - $consultation->getData('discount_rate'))
            //PricePerHour*DurationHours*(1-DiscountRate)?>

            (<?=$consultation->getData('discount_rate') * 100 ?>%)
    <hr>
<?php endforeach; ?>