<?php
/** @var \Perspective\HomeworkDatabase\ViewModel\GetDataByTitleFilter $viewModel */
$viewModel = $block->getData('viewModel');

$titleFilter = 'Unique';
$collection = $viewModel->getConsultationsByTitle($titleFilter);

echo '<h3>Завдання 7: Get Consultation Data By Title Filter</h3>';
echo('<h3>Filter: ' . $titleFilter . '</h3>');

foreach ($collection as $consultation): ?>
    <p>
        Consultation ID: <?= $consultation->getData('consultation_id') ?><br>
        Title: <?= $consultation->getData('title') ?><br>
        Duration: <?= $consultation->getData('duration_hours') ?>h<br>
        Datetime: <?= $consultation->getData('consultation_datetime') ?><br>
        Customer ID: <?= $consultation->getData('customer_id') ?><br>
        Discount: <?= $consultation->getData('discount_rate') * 100 ?>%<br>
        Price Per Hour: <?= $consultation->getData('price_per_hour') ?>
    </p>
    <hr>
<?php endforeach; ?>


